### PR TITLE
Fix/forward auth redirect

### LINKED ISSUE #54: after login, the /_verify check redirects to the wrong URI
I have an app running at `my-app.my-domain.com`, and saml-auth-proxy running at `sso.my-domain.com`, and forward_auth setup to `https://sso.my-domain.com/_verify`.

Problem:
1. user visits `my-app.my-domain.com`
2. is redirected to login and logs in
3. gets redirected to `sso.my-domain.com/_verify` instead of the original `my-app.my-domain.com`.

To help, the forward_auth protocol includes two headers to the /_verify request -- `X-Forwarded-Method` and `X-Forwarded-Uri`.

Potential solution?
The cookie tracker could detect the `/_verify` path and use `x-forwarded-uri` header instead of `r.URL.String` in line https://github.com/itzg/saml-auth-proxy/blob/565baf90e335635f41ac28ac968884d11d57c105/server/request_tracker_cookie.go#L37

If it helps, I have an old old fork that does this (probably not the best check): https://github.com/kennethklee/saml-auth-proxy/blob/4cba73af48ba5aebcb5f22d16a6231a542bcb112/server/request_tracker_cookie.go#L27-L34

### PR DESCRIPTION
**Pull request by kennethklee**
Fixes #54 

This changes:
- Adds check for `X-Forwarded-Uri and builds redirect URI from it. Based on https://doc.traefik.io/traefik/middlewares/http/forwardauth/#forward-request-headers
- Fixes usage formatting for `AttributeHeaderWildcard`
- gofmt seems to have moved the require zap, lower in the list
- Adds `--auth-verify` flag to enable `/_verify` endpoint and trust x-forwarded headers

### CODE REVIEW

**Comment by kennethklee** [comment]
realized, this needs a flag to enable

File: server/server.go [hunk 1]
```diff
@@ -125,8 +126,10 @@ func fetchMetadata(ctx context.Context, client *http.Client, idpMetadataUrl *url
 		}
 		return idpMetadata, nil
 	} else {
-		reqCtx, _ := context.WithTimeout(ctx, fetchMetadataTimeout)
-		return samlsp.FetchMetadata(reqCtx, client, *idpMetadataUrl)
+		reqCtx, cancel := context.WithTimeout(ctx, fetchMetadataTimeout)
+		desc, err := samlsp.FetchMetadata(reqCtx, client, *idpMetadataUrl)
+		cancel()
```
Comment (itzg) [inline server/server.go:131]: What is this doing?

**Review by itzg — COMMENTED** [review]
Thanks!

File: server/server.go (hunk 1 above)
Comment (kennethklee) [reply server/server.go:131]: oops i wasn't supposed to check that in

**Comment by kennethklee** [comment]
@itzg ready for review!

**Review by itzg — APPROVED** [review]
Awesome! Thanks.

**Comment by itzg** [comment]
It’s released https://github.com/itzg/saml-auth-proxy/releases/tag/1.11.0
